config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  resources :documents
  root "employees#index"
  resources :employees
  # public pages routes
  get "about" => "pages#about_us"
  get "contract" => "pages#contract_us"
  get "privacy" => "pages#privacy_policy"
  get "trams" => "pages#trams_and_conditions"

end

app/views/shared/_dummy_content.html.erb

<p class="lead">
  There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.
</p>

<p class="lead">
  There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.
</p>

<p class="lead">
  There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.
</p>

app/views/shared/_employee_from.html.erb
<%= form_with model: employee do |form| %>
  <div class="row">
    <div class="col-lg-4">
      <div class="form-group">
        <%= form.label :first_name, class: "mb-2" %>
        <%= form.text_field :first_name, class: "form-control form-control-lg rounded-0" %>
        <% @employee.errors.full_messages_for(:first_name).each do |message| %>
          <div class="text-danger mt-1"><%= message %></div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-4">
      <div class="form-group">
        <%= form.label :last_name, class: "mb-2" %>
        <%= form.text_field :last_name, class: "form-control form-control-lg rounded-0" %>
        <% @employee.errors.full_messages_for(:last_name).each do |message| %>
          <div class="text-danger mt-1"><%= message %></div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-4">
      <div class="form-group">
        <%= form.label :email, class: "mb-2" %>
        <%= form.email_field :email, class: "form-control form-control-lg rounded-0" %>
        <% @employee.errors.full_messages_for(:email).each do |message| %>
          <div class="text-danger mt-1"><%= message %></div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-4">
      <div class="form-group">
        <%= form.label :phone, class: "mb-2" %>
        <%= form.number_field :phone, class: "form-control form-control-lg rounded-0" %>
        <% @employee.errors.full_messages_for(:phone).each do |message| %>
          <div class="text-danger mt-1"><%= message %></div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-4">
      <div class="form-group">
        <%= form.label :date_of_birth, class: "mb-2" %>
        <%= form.date_field :date_of_birth, class: "form-control form-control-lg rounded-0" %>
        <% @employee.errors.full_messages_for(:date_of_birth).each do |message| %>
          <div class="text-danger mt-1"><%= message %></div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-4">
      <div class="form-group">
        <%= form.label :designation, class: "mb-2" %>
        <%= form.text_field :designation, class: "form-control form-control-lg rounded-0" %>
        <% @employee.errors.full_messages_for(:designation).each do |message| %>
          <div class="text-danger mt-1"><%= message %></div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-4">
      <div class="form-group">
        <%= form.label :address, class: "mb-2" %>
        <%= form.text_field :address, class: "form-control form-control-lg rounded-0" %>
        <% @employee.errors.full_messages_for(:address).each do |message| %>
          <div class="text-danger mt-1"><%= message %></div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12 mt-4 bt-5 rounded-0">
      <%= form.submit class: "btn btn-primary rounded-0 " %>
      <%= link_to "Back to Employees", employees_path, class: "btn btn-outline-primary rounded-0" %>
    </div>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "HR Management", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Setting
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item">Sign in as <%= current_user.email %></a></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, class: "dropdown-item", method: :delete, data: { confirm: "Are you sure to Log out!" } %></li>
            </ul>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_link.html.erb
<footer class="bg-dark text-white mt-5 py-4">
  <div class="container text-center">
    <h2 class="mb-3">Links</h2>
    <div class="d-flex flex-column flex-md-row justify-content-center gap-3">
      <%= link_to "About Us", about_path, class: "text-danger text-decoration-none" %>
      <%= link_to "Contact Us", contract_path, class: "text-danger text-decoration-none" %>
      <%= link_to "Privacy Policy", privacy_path, class: "text-danger text-decoration-none" %>
      <%= link_to "Terms & Conditions", trams_path, class: "text-danger text-decoration-none" %>
    </div>
    <p class="mt-3 mb-0">&copy; <%= Time.current.year %> Your Company. All rights reserved.</p>
  </div>
</footer>