config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  resources :documents
  root "employees#index"
  resources :employees
  # public pages routes
  get "about" => "pages#about_us"
  get "contract" => "pages#contract_us"
  get "privacy" => "pages#privacy_policy"
  get "trams" => "pages#trams_and_conditions"

end

app/models/document.rb
class Document < ApplicationRecord
  DOC_TYPES = %w[NID Marksheet AddressProof Others]
  belongs_to :employee
  has_one_attached :image
  validates :name, :doc_type, presence: true
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: %i[ show edit update destroy ]

  # GET /documents or /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1 or /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents or /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to documents_path, notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to documents_path, notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    @document.destroy!

    respond_to do |format|
      format.html { redirect_to documents_path, status: :see_other, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.expect(document: [ :name, :doc_type, :employee_id , :image])
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document.html.erb
<div id="<%= dom_id document %>">
  <p>
    <strong>Name:</strong>
    <%= document.name %>
  </p>

  <p>
    <strong>Doc type:</strong>
    <%= document.doc_type %>
  </p>

  <p>
    <strong>Employee:</strong>
    <%= document.employee_id %>
  </p>

</div>

app/views/documents/_form.html.erb
<%= form_with(model: document) do |form| %>
  <div class="row">
    <div class="col-lg-5">
      <div class="form-group">
        <%= form.label :name, class: "mb-2" %>
        <%= form.text_field :name, class: "form-control form-control-lg rounded-0" %>
        <% @document.errors.full_messages_for(:name).each do |message| %>
          <div class="text-danger mt-1"><%= message %></div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-5">
      <div class="form-group">
        <%= form.label :doc_type, class: "mb-2" %>
        <%= form.select :doc_type,options_for_select(Document::DOC_TYPES,selected:document.doc_type),{prompt:"Select document type"},class: "form-select form-select-lg rounded-0" %>
        <% @document.errors.full_messages_for(:doc_type).each do |message| %>
          <div class="text-danger mt-1"><%= message %></div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-5">
      <div class="form-group">
        <%= form.label :employee_id, class: "mb-2" %>
        <%= form.select :employee_id,options_for_select(Employee.all.map{|employee|[employee.name_with_email,employee.id]},selected:document.employee_id),{prompt:"Select employee"} ,class: "form-select form-select-lg rounded-0" %>
        <% @document.errors.full_messages_for(:employee_id).each do |message| %>
          <div class="text-danger mt-1"><%= message %></div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-5">
      <div class="form-group">
        <%= form.label :image , class: "mb-2" %> <br>
        <%= form.file_field :image %>
        <% @document.errors.full_messages_for(:employee_id).each do |message| %>
          <div class="text-danger mt-1"><%= message %></div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12 mt-4 bt-5 rounded-0">
      <%= form.submit class: "btn btn-primary rounded-0 " %>
      <%= link_to "Back to Documents", documents_path, class: "btn btn-outline-warning rounded-0" %>
    </div>
  </div>
<% end %>

app/views/documents/edit.html.erb
<div class="col-lg-12">
  <% content_for :title, "Editing document" %>

  <h1>Editing document</h1>

  <%= render "form", document: @document %>
</div>

app/views/documents/index.html.erb
<!--<p style="color: green"><%#= notice %></p>-->

<%# content_for :title, "Documents" %>

<!--<h1>Documents</h1>-->

<!--<div id="documents">-->
<%# @documents.each do |document| %>
<%#= render document %>
<!--    <p>-->
<%#= link_to "Show this document", document %>
<!--    </p>-->
<%# end %>
<!--</div>-->

<%#= link_to "New document", new_document_path %>

<div class="col-lg-12">
  <%= flash[:notice] %>
  <div class="card rounded-0 mt-5 mb-5">
    <h2 class="text-center">List of Documents </h2>
  </div>
  <%= link_to "Create New", new_document_path, class: "btn btn-primary btn mb-4 rounded-0" %>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>Name</th>
      <th>Doc Type</th>
      <th>Employee Name</th>
      <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.name %></td>
        <td><%= document.doc_type %></td>
        <td><%= link_to "#{document.employee.name}",employee_path(document.employee) %></td>
        <td>
          <%= link_to "View", document_path(document), class: "btn btn-outline-info btn-sm rounded-0" %>
          <%= link_to "Edit", edit_document_path(document), class: "btn btn-outline-warning btn-sm rounded-0" %>
          <%= link_to "Delete", document_path(document), method: :delete, data: { confirm: "Are you sure you want to delete this employee?" }, class: "btn btn-outline-danger btn-sm rounded-0" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/documents/new.html.erb
<% content_for :title, "New document" %>

<h1>New document</h1>

<%= render "form", document: @document %>

<br>

app/views/documents/show.html.erb
<!--<p style="color: green"><%#= notice %></p>

<%#= render @document %>

<div>
  <%#= link_to "Edit this document", edit_document_path(@document) %> |
  <%#= link_to "Back to documents", documents_path %>

  <%#= button_to "Destroy this document", @document, method: :delete %>
</div>-->

<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <div class="card shadow-lg border-0 rounded-4">
        <div class="card-body px-5 py-4">
          <h2 class="text-center mb-4 fw-bold text-primary">Document Details</h2>

          <div class="mb-3">
            <div class="d-flex justify-content-between align-items-center border-bottom pb-2">
              <strong>Employee Name:</strong>
              <span><%= @document.employee.name %></span>
            </div>
          </div>

          <div class="mb-3">
            <div class="d-flex justify-content-between align-items-center border-bottom pb-2">
              <strong>Document Name:</strong>
              <span><%= @document.name %></span>
            </div>
          </div>

          <div class="mb-4">
            <div class="d-flex justify-content-between align-items-center border-bottom pb-2">
              <strong>Document Type:</strong>
              <span><%= @document.doc_type %></span>
            </div>
          </div>

          <% if @document.image.attached? %>
            <div class="text-center mt-5 mb-4">
              <%= image_tag @document.image, class: "img-fluid rounded shadow-sm", alt: "Document Image" %>
            </div>
          <% end %>

          <div class="text-center">
            <%= link_to "Back to List", documents_path, class: "btn btn-outline-secondary me-2 px-4" %>
            <%= link_to "Edit", edit_document_path(@document), class: "btn btn-primary px-4" %>
            <%= button_to "Delete", @document, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger mt-2 ms-2 px-4" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>